# Generated by Django 3.2.11 on 2022-02-01 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20220126_1854'),
        ('basketapp', '0002_auto_20220201_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product'),
        ),
    ]
