# Generated by Django 3.2.11 on 2022-01-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.PositiveIntegerField(default=0, verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='цена'),
        ),
    ]
